### ISSUE TITLE
Allow 'follow' feature on organizations

### ISSUE THREAD

**Issue by xemasiv** [dear-github/dear-github#308] opened 2018-06-24 01:12 UTC
It's fucking hard to track organizations here in github, you can only follow the people behind them which sucks. No chance of seeing them in my home feed whenever they publish something new in the name of the org.

Aye? AYE!

**Comment by Mottie** [comment] 2018-06-25 14:41
Duplicate of #121.

**Closed** 2018-06-27 15:59 UTC
